name: Build and Upload rootfS and Push Image

on:
  workflow_dispatch:
  schedule:
    # Runs every week on Monday at 00:00 UTC
    - cron: "0 0 * * 1"

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-upload-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files
        run:
            cp bootstrap.list "$PWD/scripts"
            cp packages.list "$PWD/scripts"
            cp "$PWD/hooks/post_bootstrap.sh" "$PWD/scripts"
            cp "$PWD/hooks/post_install.sh" "$PWD/scripts"

      - name: Build rootfs
        run: |
          docker run \
            --env PS1="ADC(\#)[\d \T:\w]\\$ " \
            --interactive \
            --privileged \
            --rm \
            --volume "$PWD/build:/build" \
            --volume "$PWD/scripts:/scripts" \
            "index.docker.io/library/archlinux:latest" \
            /bin/bash -c "/scripts/make-rootfs.sh"

      - name: Upload rootfs tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: zenithos-rootfs.tar.zst
          path: ./build/zenithos-rootfs-*.tar.zst

      - name: Upload rootfs tarball artifact checksum
        uses: actions/upload-artifact@v4
        with:
          name: zenithos-rootfs.tar.zst.SHA256
          path: ./build/zenithos-rootfs-*.tar.zst.SHA256

      - name: Set up Podman
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build container image
        run: |
          BUILD_DATE=$(date +%Y%m%d)
          TAG="$BUILD_DATE-bootc"
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/zenith-os:$TAG"
          podman build -t "$IMAGE_NAME" -f Containerfile .

      - name: Push container image to GHCR
        run: |
          BUILD_DATE=$(date +%Y%m%d)
          TAG="$BUILD_DATE-boot"
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/zenith-os:$TAG"
          podman push "$IMAGE_NAME"
